CREATE DATABASE DECEMBER_BATCH
DROP DATABASE DECEMBER_BATCH

CREATE TABLE DEPARTMENTS
( DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE)

CREATE TABLE STUDENTS
( STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
AGE INT CHECK(AGE>=17),
DEPARTMENT_ID INT FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENT_ID))

CREATE TABLE COURSES
( COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(50) NOT NULL,
DEPARTMENT_ID INT FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENT_ID))

INSERT INTO DEPARTMENTS
SELECT 1,'CSE' UNION ALL
SELECT 2,'ELECTRICAL' UNION ALL
SELECT 3,'CIVIL' UNION ALL
SELECT 4,'MECHANICAL' UNION ALL
SELECT 5,'ELECTRONICS'

INSERT INTO STUDENTS
SELECT 1001,'AJITH',23,2 UNION ALL
SELECT 2002,'BROOK',26,4 UNION ALL
SELECT 3003,'RAINA',27,1 UNION ALL
SELECT 4004,'SURYA',29,3 UNION ALL
SELECT 5005,'VIJAY',28,5

INSERT INTO COURSES
SELECT 001,'DBMS',1 UNION ALL
SELECT 002,'THERMODYNAMICS',4 UNION ALL
SELECT 003,'CIRCUITS',2 UNION ALL
SELECT 004,'STRUCTURES',3 UNION ALL
SELECT 005,'AI',1

SELECT * FROM STUDENTS
WHERE AGE > 20

SELECT * FROM COURSES
WHERE DEPARTMENT_ID = 1

SELECT * FROM STUDENTS
WHERE DEPARTMENT_ID = 5

SELECT * FROM STUDENTS
WHERE AGE BETWEEN 18 AND 22

SELECT *
FROM STUDENTS INNER JOIN DEPARTMENTS ON STUDENTS.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID

SELECT *
FROM COURSES LEFT JOIN DEPARTMENTS ON COURSES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID

SELECT *
FROM STUDENTS RIGHT JOIN COURSES ON STUDENTS.DEPARTMENT_ID = COURSES.DEPARTMENT_ID