CREATE DATABASE STUDENT_MANAGEMENT
USE STUDENT_MANAGEMENT

CREATE TABLE STUDENTS
(STUDEENT_ID INT PRIMARY KEY IDENTITY(1,1),
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
DOB DATE NOT NULL,
GENDER CHAR(1) CHECK(GENDER IN('M','F')),
MARKS INT CHECK (MARKS BETWEEN 0 AND 100),
ADMISSION_DATE DATETIME DEFAULT GETDATE()
)

INSERT INTO STUDENTS
SELECT 'VIRENDRA','SEHWAG','1978-10-20','M',99,'2005-04-23' UNION ALL
SELECT 'RISHAB','PANT','1997-10-04','M',97,'2014-06-08' UNION ALL
SELECT 'SUREH','RAINA','1986-11-27','M',100,'2010-04-27' UNION ALL
SELECT 'MOHAMMED','SHAMI','1990-09-03','M',95,'2012-05-07' UNION ALL
SELECT 'RADHA','YADHAV','2000-04-21','F',95,'2017-05-22' UNION ALL
SELECT 'HARLEEN','DEOL','1998-06-21','F',92,'2015-05-21' UNION ALL
SELECT 'SHREYANKA','PATIL','2002-07-31','F',85,'2019-06-24'

SELECT * INTO STUDENTS_BACKUP FROM STUDENTS

SELECT DATEDIFF(YEAR,DOB,GETDATE()) AS AGE,* FROM STUDENTS
SELECT DATEPART(YEAR,ADMISSION_DATE) AS ADMISSION_YEAR,
DATEPART(MONTH,ADMISSION_DATE) AS ADMISSION_MONTH FROM STUDENTS
SELECT * FROM STUDENTS WHERE ADMISSION_DATE >= GETDATE()-30


SELECT MAX(MARKS) AS HIGHEST_MARKS FROM STUDENTS
SELECT MIN(MARKS) AS LOWEST_MARKS FROM STUDENTS
SELECT AVG(MARKS) AS AVERAGE_MARKS FROM STUDENTS

SELECT COUNT(GENDER) AS MALES FROM STUDENTS WHERE GENDER='M'
SELECT COUNT(GENDER) AS FEMALES FROM STUDENTS WHERE GENDER='F'
SELECT COUNT(DOB) AS '2K' FROM STUDENTS WHERE YEAR(DOB) > 2000