CREATE TABLE SALESMAN
(SALESMAN_ID INT,
SALESMAN_NAME CHAR(50),
COMMISSION INT,
CITY CHAR(50),
AGE CHAR(2)
)

INSERT INTO SALESMAN
SELECT 101,'JOE',50,'CALIFORNIA',17 UNION ALL
SELECT 102,'SIMON',75,'TEXAS',25 UNION ALL
SELECT 103,'JESSIE',105,'FLORIDA',35 UNION ALL
SELECT 104,'DANNY',100,'TEXAS',22 UNION ALL
SELECT 105,'LIS',65,'NEW JERSY',30

CREATE TABLE CUSTOMER
(SALESMAN_ID INT,
CUSTOMER_ID INT,
CUSTOMER_NAME CHAR(50),
PURCHASE_AMOUNT INT
)

INSERT INTO CUSTOMER
SELECT 101,2345,'ANDREW',550 UNION ALL
SELECT 103,1575,'LUCKY',4500 UNION ALL
SELECT 104,2345,'ANDREW',4000 UNION ALL
SELECT 107,3747,'REMONA',2700 UNION ALL
SELECT 110,4004,'JULIA',4545 

CREATE TABLE ORDERS
(ORDER_ID INT,
CUSTOMER_ID INT,
SALESMAN_ID INT,
ORDER_DATE DATE,
AMOUNT INT
)

INSERT INTO ORDERS
SELECT 5001,2345,101,'2021-07-04',550 UNION ALL
SELECT 5003,1234,105,'2022-02-15',1500

SELECT * FROM SALESMAN
SELECT * FROM CUSTOMER
SELECT ORDER_ID,CUSTOMER_ID,SALESMAN_ID,CONVERT(VARCHAR(10),ORDER_DATE,5),AMOUNT FROM ORDERS

-- EXECUTING THE QUERY

INSERT INTO ORDERS
SELECT 5005,4004,110,'2023-05-23',2500

ALTER TABLE SALESMAN
ALTER COLUMN SALESMAN_ID INT NOT NULL
ALTER TABLE SALESMAN
ADD CONSTRAINT PK_SALESMAN_ID PRIMARY KEY(SALESMAN_ID)

ALTER TABLE SALESMAN
ADD CONSTRAINT DT_CITY DEFAULT('NOT GIVEN') FOR CITY

ALTER TABLE CUSTOMER
ALTER COLUMN SALESMAN_ID INT NOT NULL
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_SALESMAN FOREIGN KEY(SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID) 
-- NOT ABLE TO INSERT FOREIGN KEY CONSTRAINT BECAUSE SOME OF SALESMAN_ID IN CUSTOMER TABLE IS NOT IN SALESMAN TABLE

ALTER TABLE CUSTOMER
ALTER COLUMN CUSTOMER_NAME CHAR(50) NOT NULL

SELECT * FROM CUSTOMER
WHERE CUSTOMER_NAME LIKE '%N' AND PURCHASE_AMOUNT > 500

SELECT SALESMAN_ID FROM SALESMAN
UNION
SELECT SALESMAN_ID FROM CUSTOMER

SELECT SALESMAN_ID FROM SALESMAN
UNION ALL
SELECT SALESMAN_ID FROM CUSTOMER

SELECT ORDER_DATE,SALESMAN_NAME,CUSTOMER_NAME,COMMISSION,CITY FROM SALESMAN
INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
INNER JOIN ORDERS ON CUSTOMER.SALESMAN_ID = ORDERS.SALESMAN_ID
WHERE PURCHASE_AMOUNT BETWEEN 500 AND 1500

SELECT * FROM SALESMAN
RIGHT JOIN ORDERS ON SALESMAN.SALESMAN_ID = ORDERS.SALESMAN_ID