CREATE TABLE CUSTOMER
(CUSTOMER_ID INT,
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
EMAIL NVARCHAR(50),
ADDRESS NVARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
ZIP INT
)

INSERT INTO CUSTOMER
SELECT 1,'JOS','BUTLER','JOS123@GMAIL.COM','TAUTON','SOMERSET','SOMERSET',123456 UNION ALL
SELECT 2,'HARRY','BROOK','HARRRY123@GMAIL.COM','KEIGHLEY','YORKSHIRE','YORKSHIRE',133456 UNION ALL
SELECT 3,'JOE','ROOT','ROOT123@GMAIL.COM','SHEFFIELD','YORKSHIRE','YORKSHIRE',133556 UNION ALL
SELECT 4,'JAMES','ANDERSON','ANDERSON@GMAIL.COM','BURNLEY','LANCASHIRE','LANCASHIRE',143456 UNION ALL
SELECT 5,'STUART','BROAD','BROAD@GMAIL.COM','BURNLEY','SAN JOSE','NOTTINGHAM',153456

SELECT * FROM CUSTOMER

-- EXECUTING THE QUERY

SELECT FIRST_NAME,LAST_NAME FROM CUSTOMER

SELECT * FROM CUSTOMER
WHERE FIRST_NAME LIKE 'G%' AND CITY = 'SAN JOSE'
SELECT * FROM CUSTOMER
WHERE CITY = 'SAN JOSE'

SELECT * FROM CUSTOMER
WHERE EMAIL LIKE '%@GMAIL%'

SELECT * FROM CUSTOMER
WHERE LAST_NAME <> '%A'