SELECT * FROM ORDERS
ORDER BY AMOUNT DESC

CREATE TABLE EMPLOYEE_DETAILS_1
(EMP_ID INT,
EMP_NAME CHAR(50),
EMP_SALARY INT
)

INSERT INTO EMPLOYEE_DETAILS_1
SELECT 1,'BUTLER',5000 UNION
SELECT 2,'ROOT',4000 UNION
SELECT 3,'BROOK',3000

CREATE TABLE EMPLOYEE_DETAILS_2
(EMP_ID INT,
EMP_NAME CHAR(50),
EMP_SALARY INT
)

INSERT INTO EMPLOYEE_DETAILS_2
SELECT 3,'BROOK',3000 UNION
SELECT 4,'ANDERSON',4000 UNION
SELECT 5,'BROAD',5000

SELECT * FROM EMPLOYEE_DETAILS_1
UNION
SELECT * FROM EMPLOYEE_DETAILS_2

SELECT * FROM EMPLOYEE_DETAILS_1
UNION ALL
SELECT * FROM EMPLOYEE_DETAILS_2

SELECT * FROM EMPLOYEE_DETAILS_1
INTERSECT
SELECT * FROM EMPLOYEE_DETAILS_2

SELECT * FROM EMPLOYEE_DETAILS_1
EXCEPT
SELECT * FROM EMPLOYEE_DETAILS_2

SELECT * FROM EMPLOYEE_DETAILS_2
EXCEPT
SELECT * FROM EMPLOYEE_DETAILS_1
